### ISSUE TITLE
[Docs]Add RVM Description to SMP Documentation

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/service-mesh-performance#102]
**Current State:**
Windows users are having issues using Jekyll and there's no description to help with that.

**Desired State:**
Provide a description of RVM to the `set up your development environment` section of the SMP Doc by adding this line.

` Note: Windows users can run Jekyll by following the [Windows Installation Guide](https://jekyllrb.com/docs/installation/windows/) and also install Ruby Version Manager [RVM](https://rvm.io) - a command-line tool which allows you to easily install, manage and work with multiple ruby environments on your local machine.Alternatively, if you're running Windows 10, updated to version 1903 Build 18362 or higher you can upgrade to Windows Subsystem for Linux [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)`

The additional lines can be added right after *Jekyll Docs* .👍🏽

---
**Contributor Resources**
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by oyinmi** [comment]
Can someone please assign this to me?

**Comment by JubayerJoy** [comment]
@oyinmi good luck to you! 🎈

**Comment by oyinmi** [comment]
@JubayerJoy Thank you.
