### ISSUE TITLE
[Site] Remove extra padding

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#103]
**Description**
The Resources and Connect sections have unnecessary top and bottom padding. Remove the extra padding present in these sections and adjust the existing content accordingly to make the sections look more presentable.

**Screenshots**

![Screenshot_2020-08-25 Service Mesh Performance Specification(1)](https://user-images.githubusercontent.com/34476976/91197845-7288fb80-e719-11ea-9eef-227a3fc88ffd.png)

**Comment by lumenCodes** [comment]
Hey @chandrashritii there is no additional resource for this issue and is there a suggested padding for the sections?

**Comment by chandrashritii** [comment]
@lumenCodes There is no suggested padding as such. You will have to experiment a bit here and see what looks most appropriate. I'm not sure what you mean by additional resources. Please do let me know and I'll help you out in any way I can 🎈

**Comment by shubhamgupta2956** [comment]
Hello everyone. Is this issue fixed as I can not see any extra padding in the [website](https://smp-spec.io/)

![2020-09-13_18-33-47-](https://user-images.githubusercontent.com/43504292/93018767-c9367680-f5ef-11ea-862b-779ebfd2e913.png)

**Comment by Neilblaze** [comment]
@shubhamgupta2956 yup it has been fixed with #122
