### ISSUE TITLE
[Site] Fix header size

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#104]
**Description**

Reduce the header length to make it more compact and accordingly resize the smp logo to fit the header. This will take some attempts at playing around with different sizes for the header and the smp logo to achieve the perfect combination.

**Steps to reproduce**
1. Go to https://smp-spec.io/
2. Observe the header

**Comment by St80ene** [comment]
I would love to take up this task

**Comment by chandrashritii** [comment]
Go ahead 👍  @St80ene

**Comment by chandrashritii** [comment]
@St80ene Thank you for taking this on! Let me know if you need any help 🎈

**Comment by Neilblaze** [comment]
Closed by #122
