### ISSUE TITLE
[Site] Reformat the footer section

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#105]
**Description**

Currently, the footer section houses the social icons. The section should be reformatted to include -
- A site guide
- Social buttons
- A twitter window

Inspiration can be taken from the [Meshery](https://meshery.io/) site:

![Screenshot_2020-08-25 Meshery The Service Mesh Management Plane](https://user-images.githubusercontent.com/34476976/91199435-83d30780-e71b-11ea-85cd-80edf2cffad2.png)

**Comment by JubayerJoy** [comment]
Hi @chandrashritii, I would love to take this issue!

**Comment by chandrashritii** [comment]
@JubayerJoy Sure. Go ahead 👍

**Comment by JubayerJoy** [comment]
@Neilblaze is working on this so assigning it to him 🚀
