### ISSUE TITLE
Add Reminder in the Welcome Bot to Star SMP Project

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/service-mesh-performance#107]
**Current Behavior**
 A welcome bot has been configured to usher in contributors new to this project. However, a reminder to star the project is missing in the message.

**Desired Behavior**
 The [config.yml](https://github.com/layer5io/service-mesh-performance/blob/master/.github/config.yml) should be updated, you can take a cue from the highlighted [line 22](https://github.com/layer5io/meshery-consul/blob/master/.github/config.yml#L22)

---
**Resources**

**Alternatives / Additional Context**

**Comment by akashgp09** [comment]
@PluckyPrecious  Can i work on this issue ?

**Comment by PluckyPrecious** [comment]
Sure, do go ahead.

**Comment by akashgp09** [comment]
@PluckyPrecious I have made a PR for this issue. Can you Please review it.
