### ISSUE TITLE
[Site] Fix the Contributors section

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#111]
**Description**

The logos listed in the [Contributors section](https://smp-spec.io/#contributors) currently occupy two lines.

**Expected Behavior**

They should be adjusted onto the same line, either by adjusting the logo sizes or more preferably by adding a horizontal scroll to the section.

**Screenshots**

![Screenshot_2020-09-01 Service Mesh Performance Specification](https://user-images.githubusercontent.com/34476976/91883119-9b713980-eca1-11ea-9479-d67d5fceaa12.png)

**Environment:**
 - OS: Windows 10
 - Browser: Firefox
 - Device: Laptop
---
[Optional] **To Reproduce**
1. Go to https://smp-spec.io/
2. Click on `Contributors` in the header
3. See error

**Comment by oyakhilomee** [comment]
Hello @chandrashritii, I'll like to take this up!

**Comment by Ruth-ikegah** [comment]
Sure go ahead @oyakhilomee

**Comment by oyakhilomee** [comment]
Hello Ruth, I don't think I can do this currently and someone else can possibly do this to avoid me clogging up space.

**Comment by geraldmaboshe** [comment]
Hey @chandrashritii , I am interested in solving this

**Comment by JubayerJoy** [comment]
@geraldmaboshe go for it! All the best to you. 🎈

**Comment by chandrashritii** [comment]
@geraldmaboshe Thanks for taking this up!
@Neilblaze I remember you were working on this. If you have fixed it already, please do signal here.

**Comment by Neilblaze** [comment]
> @geraldmaboshe Thanks for taking this up!
> @Neilblaze I remember you were working on this. If you have fixed it already, please do signal here.

Yeah I was thinking to hop into this after fixing the footer section, but if @geraldmaboshe wants to take this, he can surely take this up! :smile:

**Comment by JubayerJoy** [comment]
Hi @Neilblaze, have you started working on #105? I'm working on that as well.

**Comment by Neilblaze** [comment]
@geraldmaboshe make sure you keep spaces for more room!

@JubayerJoy I'm working on it! But if you have nearly completed it, do let me know.

**Comment by JubayerJoy** [comment]
@Neilblaze, have done some code changes, far from finalizing. You should go ahead, can't work on this till 15th Sept.
Good luck!
