### ISSUE TITLE
[Site] List the author name and date on the blog posts

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/service-mesh-performance#112]
**Description**

In the [blog page](https://smp-spec.io/blog/) of [Service Mesh Performance](https://smp-spec.io/), currently we are missing out author name and date on the blog posts. 

**Expected Behavior**

The blog page should contain the respective author name and date on the blog posts. We can use the the style of [Layer5.io/blog](https://layer5.io/blog) for reference :)

![scr1](https://user-images.githubusercontent.com/48355572/92033884-07c76800-ed8a-11ea-8b1c-e3b8ab98ee5c.JPG)

![scr2](https://user-images.githubusercontent.com/48355572/92033901-10b83980-ed8a-11ea-9988-9c217dc3789c.JPG)

NOTE : If anyone wants to fix the blog card padding issue in [blog](https://smp-spec.io/blog/) page, he/she might open a new issue regarding it & start fixing it!

**Comment by leecalcote** [comment]
@Neilblaze many people coming to look at this site. I'm making some quick updates. I added blog author and date to the page layout. The name and date are still missing on the posts_grid. 

You can change how this is done in the page layout (or create a layout for posts). We just needed something quick.

**Comment by Neilblaze** [comment]
I'm on it :zap:

**Comment by leecalcote** [comment]
Thank you, sir.
