### ISSUE TITLE
Change from SMPS to SMP as the package name

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#114]
**Description**
Stale references to SMPS are still present in the proto files and package names - https://github.com/layer5io/service-mesh-performance/blob/master/smps.proto#L3

**Expected Behavior**
These should be SMP.

**Comment by kalradev** [comment]
Great !!
This will get me started with SMP.

**Comment by Neilblaze** [comment]
@kalradev do you want to take this issue?

**Comment by kalradev** [comment]
Hey Lee, 

I have few questions related to this.

1. Why is generated go files in perf directory when they are specified to be in spec directory in the protos.
2. Are we using prototool in this project. There is a yaml file is it of some use?
3. Are we using the generated code or the proto files in other projects?
4. Do we want the generated package to be named as spec or SMP?

**Comment by kalradev** [comment]
Protobuf style guide - https://developers.google.com/protocol-buffers/docs/style
Do we want to follow the style guide. Some names need to be changed if we do so.
