### ISSUE TITLE
[Site] Blog section - revamp the footer

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#121]
**Description**

Currently, the footer section on the [blog page](https://smp-spec.io/blog/spec/getting-started-with-service-mesh-performance-analysis) of the smp-spec.io site isn't differentiated from the blog content. 

**Expected Behavior**

The footer section should be differentiated from the blog content by either making the footer background a different color or adding the option for signing up for the newsletter or some other appropriate way. Suggestions are welcome. The change should be made in the blog page template so that it can be reflected across all blog posts. This will involve some experimenting with layouts to achieve the perfect design.

**Screenshots**

![Screenshot_2020-09-07 Service Mesh Performance Specification](https://user-images.githubusercontent.com/34476976/92408195-6447d000-f15a-11ea-9ac6-e74b89ea154c.png)

**Comment by JubayerJoy** [comment]
Hi @chandrashritii, I am fixing the footer section (#105), thinking of making the making background-color [222222](https://www.color-hex.com/color/222222) and text color as `aliceblue` (both inspired by meshery.io).

<img src = "https://imgur.com/Xaq8pnW.png">

#### Though this problem should be resolved by footer fix, I strongly recommend adding a newsletter section.

**Comment by chandrashritii** [comment]
Adding a newsletter would be a good idea here @JubayerJoy. Highlighting a few issues with the footer here:
- There is too much empty space. 
- The social icons should be larger in size
- The text "Copyright ..." should be larger in size.

Adding a condensed version of the newsletter would definitely make it look better. @Nikhil-Ladha, @Neilblaze, @leecalcote , @Jashpatel1 Any suggestions?

**Comment by Jashpatel1** [comment]
> Adding a newsletter would be a good idea here @JubayerJoy. Highlighting a few issues with the footer here:
> - There is too much empty space. 
> - The social icons should be larger in size
> - The text "Copyright ..." should be larger in size.
> 
> Adding a condensed version of the newsletter would definitely make it look better. @Nikhil-Ladha, @Neilblaze, @leecalcote , @Jashpatel1 Any suggestions?

Can you try keeping all the icons in a single line and the copyright text in the next line?

**Comment by JubayerJoy** [comment]
The footer section (#105) is undergoing a **complete** redesign by @Neilblaze. None of it will remain the same, i.e. `social`, `copyright`.
My point was as I was going to change the **background color** to [222222](https://www.color-hex.com/color/222222), which should have eliminated this issue, but as Neil is working on this instead, he might have a different view.

Also, It would be nicer if we could let people comment on the blog posts getting the questions about the article answered by the organization. It might be tricky to implement but surely will good <strike>user</strike> reader experience. @leecalcote, @chandrashritii how does it sound?

P.S. I think, blog post page looks  "incomplete" without newsletter section.

**Comment by KarenEfereyan** [comment]
Is this issue still open? @lolyparty if it is look out for it

**Comment by lolyparty** [comment]
Thanks @KarenEfereyan, I think @JubayerJoy is on it

**Comment by KarenEfereyan** [comment]
Ill be on the lookout for more issues

**Comment by JubayerJoy** [comment]
Hi @KarenEfereyan!
Feel free to dive in, this issue is still open, I think no one is working on it. Thank you for your interest!

Get in touch with @Neilblaze, he is redesigning the footer section of the site (#105). To reuse color scheme and patterns he is using, collaboration is required.

@chandrashritii give Karen some pointers on this.

Cheers. :ballon:

**Comment by KarenEfereyan** [comment]
Thanks so much @JubayerJoy but @lolyparty would want to work on it

**Comment by JubayerJoy** [comment]
@KarenEfereyan, sure!
Good luck @lolyparty.

**Comment by lolyparty** [comment]
Thank you @KarenEfereyan @JubayerJoy. I really appreciate. 
@chandrashritii I'd be working on this together with @Neilblaze

**Comment by Neilblaze** [comment]
Feel free to ping me on slack :) @lolyparty

**Comment by chandrashritii** [comment]
That's great @lolyparty. Go ahead 👍  Please do make sure you collaborate with @Neilblaze on the color scheme.

**Comment by lolyparty** [comment]
> That's great @lolyparty. Go ahead 👍 Please do make sure you collaborate with @Neilblaze on the color scheme.

Sure

**Comment by Neilblaze** [comment]
Closed with #134
