### ISSUE TITLE
[Site] Drop "Specification" in meta property "og:title"

### ISSUE THREAD

**Issue by JubayerJoy** [layer5io/service-mesh-performance#126]
**Description**

Smp-spec.io project has dropped `specification` a long time ago. But in `head` section `<meta name="title" property="og:title" content="Service Mesh Performance Specification">`  is still there.
**Expected Behavior**

Change the tag to `<meta name="title" property="og:title" content="Service Mesh Performance">`

**To Reproduce**
1. Go to smp-specs.io
2. Open `html` code
3. Search for `specification`

**Comment by eliteReaper** [comment]
Hello, could I be assigned this issue ?
