### ISSUE TITLE
[Docs] Remove Google Logo from smp-spec.io

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#129]
**Current State:**
While individual Googler's have collaborated on SMP, Google as an entity has not publicly partnered / is not necessarily endorsing SMP currently.

**Desired State:**
Google's logo should not be present on the smp-spec.io site.

---
**Contributor Resources**
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by geraldmaboshe** [comment]
@leecalcote  though it's already assigned to @Neilblaze but can I take it up?

**Comment by leecalcote** [comment]
@geraldmaboshe that would be great, yes.
