### ISSUE TITLE
[Site] Create a difference in color on either side of the blog posts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#138]
**Current Behavior**
A lack of formatting on the individual blog pages has them not looking as much like articles as they could be.

**Desired Behavior**
Add color to the left and right margins or some other styling to the blog post page layout to offset the text from the page.

**Screenshot**
<img width="1537" alt="Screen Shot 2020-09-29 at 8 04 40 AM" src="https://user-images.githubusercontent.com/7570704/94562186-a2e91b80-022a-11eb-842f-1eb442bd9f2e.png">

**Comment by Aniruddha-Shriwant** [comment]
Hey @leecalcote , well not so sure that I can solve this at all :|
but I will like to try to do it :)

**Comment by Neilblaze** [comment]
@Aniruddha-Shriwant Sure! Go for it. :+1:

**Comment by Aniruddha-Shriwant** [comment]
Well sorry for late, I was getting some errors in setting up the dev environment on Windows,
I'm currently working to resolve the errors occurring at setup :)

**Comment by Neilblaze** [comment]
No issues, take your time! :smile:

**Comment by Aniruddha-Shriwant** [comment]
> No issues, take your time! 😄

Thanks a lot! :-)

**Comment by pythonphoenix** [comment]
I will get back to you in 4 hours time

**Comment by NidhiTater** [comment]
I am working on it.  A shade of the header color seems good ?

**Comment by Nikhil-Ladha** [comment]
> I am working on it. A shade of the header color seems good ?

@NidhiTater good of you to have your interest here. But, this issue is already assigned to someone. You can take a peak into other issues and comment there, I will assign you one.

**Comment by NidhiTater-Argil** [comment]
> > I am working on it. A shade of the header color seems good ?
> 
> @NidhiTater good of you to have your interest here. But, this issue is already assigned to someone. You can take a peak into other issues and comment there, I will assign you one.

Sure, please update the assignee name, otherwise others might look into this too.

**Comment by Nikhil-Ladha** [comment]
Assignee name is already updated. It is assigned to @Aniruddha-Shriwant . Check again😅

**Comment by Aniruddha-Shriwant** [comment]
> I'm currently working to resolve the errors occurring at setup :)

Hey, I'm done with my setup! 

Sorry for time consumed :( 
Will start working on this issue now :)

**Comment by L-crypt** [comment]
Can I try this issue?? thanks in advance.

**Comment by Nikhil-Ladha** [comment]
Yeah sure @L-crypt 👍🏼

**Comment by navendu-pottekkat** [comment]
@leecalcote @Nikhil-Ladha I have a suggestion and that is to wrap the blog post into a card and add a nice shadow. 

It would look like this as shown below:

![Screenshot from 2020-11-07 19-27-21](https://user-images.githubusercontent.com/49474499/98443125-53eaac00-212f-11eb-9729-1b140d2114e5.png)

I think this is the best and easiest fix and it looks good too. I will make a PR if you assign it to me.

**Comment by Nikhil-Ladha** [comment]
Hmm, yeah seems better than the current one at least.

**Comment by navendu-pottekkat** [comment]
I will make a PR.
