### ISSUE TITLE
Fix the footer alignment for mobile view

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/service-mesh-performance#141]
**Current Behavior** :- 

Currently the footer section of the [SMP site](https://smp-spec.io/) is not optimized for mobile view. Most of the descriptive texts and icons are aligned to right. 

**Screenshot** :- 

![recording](https://user-images.githubusercontent.com/48355572/94775143-e84d4a80-03dc-11eb-9a58-82f503b4cbbd.gif)

**Required Changes**

- Optimize this for mobile view.

**Comment by manishkrjha** [comment]
I'd like to take this up.

**Comment by Nikhil-Ladha** [comment]
Go ahead @manishkrjha 🔥

**Comment by Nikhil-Ladha** [comment]
@Neilblaze ^^

**Comment by manishkrjha** [comment]
Also, I did try adding margins through inspecting element.

![Screenshot (282)](https://user-images.githubusercontent.com/51622948/94835181-fc219c80-042e-11eb-8986-6bcffe5d4a04.png)

![Screenshot (284)](https://user-images.githubusercontent.com/51622948/94835191-00e65080-042f-11eb-9505-68b6535319ff.png)

Is this **okay** ?

**Comment by Neilblaze** [comment]
@manishkrjha here you go - https://github.com/layer5io/service-mesh-performance/blob/master/docs/_includes/footer.html

**Comment by Neilblaze** [comment]
@manishkrjha are you still on it?
