### ISSUE TITLE
Add Nginx Service Mesh to service mesh proto file

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#143]
**Current Behavior**
NGINX Service Mesh (NSM) has recently been released.

**Desired Behavior**
This service mesh should be added to the SMP specifications' proto file - https://github.com/layer5io/service-mesh-performance/blob/63cb8b46b9ea05ceebc3a2d39adf3f6d391385e6/protos/service_mesh.proto#L27 - as 11.

**Comment by lumenCodes** [comment]
@leecalcote  I am interested in this.

**Comment by Nikhil-Ladha** [comment]
Sure @lumenCodes ! Go ahead for it!

**Comment by lumenCodes** [comment]
Oh thanks
