### ISSUE TITLE
[Site] Add KubeCon EU Talk and Video

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#146]
**Current Behavior**
The "Discreetly Studying the Effects of Individual Traffic Control Functions" talk from KubeCon EU 2020 explains SMP. 

**Desired Behavior**
This talk's video and slides should be on the [smp-spec.io](https://smp-spec.io) site. 

- video: https://layer5.io/projects/service-mesh-performance
- slides: https://calcotestudios.com/talks/decks/slides-kubecon-eu-2020-discreetly-studying-the-effects-of-individual-traffic-control-functions.html

**Comment by L-crypt** [comment]
Hey! I am a first timer ,can I contribute to this issue if possible? Thanks in advance.

**Comment by leecalcote** [comment]
Hi @L-crypt, that sounds great. Thank you.

**Comment by L-crypt** [comment]
Can I please get some clue or some reference over it? I am not able to proceed.

**Comment by dDab-panda** [comment]
Hey, I would like to try this issue out

**Comment by JubayerJoy** [comment]
@dDab-panda, sure, go ahead.

**Comment by leecalcote** [comment]
@L-crypt my apologies. I'm just now seeing your note. Here are the contribution steps - https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow. There are many other open [help-wanted](https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+) issues like this across the layer5io org that you are most welcome to pick up.
