### ISSUE TITLE
Integrate service_mesh.proto with Meshery UI performance test for service mesh names

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#150]
**Current Behavior**
The performance test page in Meshery has a static list of service mesh names.

**Desired Behavior**
The list of service mesh names in Meshery's UI can be sourced from SMP instead of being statically encoded.

---
**Screenshot**
<img width="1381" alt="Screen Shot 2020-11-02 at 4 00 07 PM" src="https://user-images.githubusercontent.com/7570704/97924112-bead7900-1d24-11eb-8d65-88ae3dff1e42.png">

**Comment by utkarsh-pro** [comment]
@leecalcote I checked this out and there are already service mesh enums defined in the `.proto` files here. So we can already get the names of the service meshes on the [meshery server](https://github.com/layer5io/meshery) from SMP in the following way:
```golang
for _, v := range SMP.ServiceMeshes_Type_name {
	if v != SMP.ServiceMeshes_INVALID_MESH.String() {
	        fmt.Println(strings.Title(strings.ToLower(strings.ReplaceAll(v, "_", " "))))
	}
}
```
It will generate the service mesh names like
```
Octarine
Tanzu
Open Service Mesh
Nginx Service Mesh
App Mesh
Consul
Linkerd
Istio
Kuma
Maesh
Network Service Mesh
```

From what I understood, we need to create an endpoint on [meshery server](https://github.com/layer5io/meshery) to serve this list. Is there something that I am missing? :thinking:

**Comment by leecalcote** [comment]
Thank you, @utkarsh-pro. My apologies - I meant to indicate that SMP will be the source of truth for the list of service meshes and that Meshery will ingest this list by importing the proto defined here.
