### ISSUE TITLE
[Site] Insert comma into thousandths place for number of tests run

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#153]
**Current Behavior**
Just like the https://layer5.io/meshery site has the number of performance tests run with a comma inserted into the thousandths place, so too should the perf test number on the smp-spec site have a comma.

<img width="641" alt="Screen Shot 2020-11-18 at 9 22 21 AM" src="https://user-images.githubusercontent.com/7570704/99557058-dec97300-2987-11eb-94df-d5001f319135.png">

<img width="1035" alt="Screen Shot 2020-11-18 at 10 22 02 AM" src="https://user-images.githubusercontent.com/7570704/99557106-ebe66200-2987-11eb-92bf-b83d9a8b5cbf.png">

**Comment by leecalcote** [comment]
@jomefavourite interested?

**Comment by jomefavourite** [comment]
Yh, I am
