### ISSUE TITLE
[Site] Add Fiserv logo to contributors section of website 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#171]
**Current Behavior**
@kenowens12 of Fiserv has long supported and contributed to the Service Mesh Performance initiative.

**Desired Behavior**
Fiserv's support and participation should be represented in the Contributors section of the website.

This logo may be used - https://upload.wikimedia.org/wikipedia/commons/8/89/Fiserv_logo.svg

---
**Contributor Resources**
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Hi @laurencun, I'll highlight this issue in case its of interest, too.

**Comment by BondaSaim** [comment]
Hello @leecalcote,
I would love to work on this,
Could you assign me to this issue ?

**Comment by leecalcote** [comment]
That be great, @BondaSaim

**Comment by BondaSaim** [comment]
Hello @leecalcote,
I have completed the task,
Could you kindly review it ?

**Comment by BondaSaim** [comment]
I have completed the task sir,
Could you please review it
