### ISSUE TITLE
[README] Update README Community Section 

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/service-mesh-performance#186]
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
![img](https://user-images.githubusercontent.com/62384659/117368468-7cbfe400-aebb-11eb-92c2-0033fd74bcfc.png)
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**

 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by Chadha93** [comment]
Hi,
@Anita-ihuman  I would I to work on this, Could you please assign me?

**Comment by Anita-ihuman** [comment]
Sure, Go ahead.

**Comment by Chadha93** [comment]
@Anita-ihuman Issue resolved, thanks for assigning.
