### ISSUE TITLE
[README] Need to fix badges 

### ISSUE THREAD

**Issue by amino19** [layer5io/service-mesh-performance#192]
**Description**

<a href="https://github.com/layer5io/service-mesh-performance/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. Plus, Align all the badges to `center`.
 
### Screenshot

**Current Behavior**

![image](https://user-images.githubusercontent.com/75872316/122430497-49d83800-cfb1-11eb-9291-87a62cdecd1d.png)

**Desired Behavior**
![image](https://user-images.githubusercontent.com/75872316/122431424-12b65680-cfb2-11eb-982f-daf8a8f3350a.png)

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
[Optional] **Reference**
- As done in <a href="https://github.com/layer5io/meshery/blob/master/README.md">meshery</a>

**Comment by mindninjaX** [comment]
@amino19 I can fix this issue. I would like to work on it.
