### ISSUE TITLE
[Site] Add SMP Project Presentation Overview Deck

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#194]
**Current State of the service-mesh-performance site**
The site is missing the project overview deck.

**Desired State of the service-mesh-performance site**
Similar as to how the Meshery overview deck is embedded into the https://meshery.io site, [the SMP overview deck](https://docs.google.com/presentation/d/1fm7Eu1T3JSBPVmdFYyyevqQLSmAMLXqzWqC7QxTHGX8/edit?usp=sharing) should be embedded underneath the "Learn more about service mesh performance" headline on the site.

<img width="1219" alt="Screen Shot 2021-06-18 at 5 39 32 PM" src="https://user-images.githubusercontent.com/7570704/122621805-477ee800-d05c-11eb-835a-0a581f4f0694.png">

**Embedding Example from Meshery.io site:**
<img width="1255" alt="Screen Shot 2021-06-18 at 5 38 24 PM" src="https://user-images.githubusercontent.com/7570704/122621724-0686d380-d05c-11eb-8d36-cf3aa43e97c9.png">

**Comment by chetak123** [comment]
can I take this issue please ?
