### ISSUE TITLE
Add CNCF logo to smp-spec.io homepage

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/service-mesh-performance#198]
**Desired State of the service-mesh-performance site**
Service Mesh Performance is now a CNCF project.

There should be a section in the [smp-spec.io](https://smp-spec.io/) home page that shows this.

Resources-

[cncf-horizontal-color.svg](https://github.com/cncf/artwork/blob/master/other/cncf/horizontal/color/cncf-color.svg)

Title of the section: "Service Mesh Performance is a Cloud Native Computing Foundation project."

**Comment by navendu-pottekkat** [comment]
@leecalcote please make any changes if necessary.

**Comment by leecalcote** [comment]
Ready for implementation. ✔️

**Comment by navendu-pottekkat** [comment]
@alphaX86 You might also want to take this up

**Comment by alphaX86** [comment]
Copy that! Will fix when the meshery.io one is updated
