### ISSUE TITLE
CI : Introduce Prototool for the protobuf

### ISSUE THREAD

**Issue by kushthedude** [layer5io/service-mesh-performance#32]
**Current Behavior**

We don't have a CI nor a linter to maintain & check consistency among the protobuf file.

**Desired Behavior**

Consider addition of [prototool](https://github.com/uber/prototool#configuration) as a CI check of the repository.

---
**Resources**

- https://github.com/uber/prototool#configuration
- https://buf.build/docs/migration-prototool
- https://github.com/bufbuild/buf

**Comment by leecalcote** [comment]
Sounds great, @kushthedude

**Comment by PluckyPrecious** [comment]
@kushthedude can we close this issue now?

**Comment by kushthedude** [comment]
No, a lot of stuff is remaining

**Comment by leecalcote** [comment]
@kalradev an opportunity to incorporate https://buf.build?

**Comment by kalradev** [comment]
Yes, I think we should use buf. Here is a comparison between the two. 
https://buf.build/docs/migration-prototool
Infact I was reading prototool documentation and in that they are recommending to checkout buf.

**Comment by kushthedude** [comment]
Buf is still in development, it is indeed great but I dont want to use any
new tool which has a long way to go for it's 1.0 release.
