### ISSUE TITLE
Spec: Remove auto-generated go-client files from the repository

### ISSUE THREAD

**Issue by kushthedude** [layer5io/service-mesh-performance#46]
**Current Behavior**

We are storing generate golang files which in our repository which should not be there.

**Desired Behavior**

Implement a CI script to generate them every time after a push or have a custom bash-script to do so.

---

**Comment by leecalcote** [comment]
Can these be added to .gitignore?

**Comment by kushthedude** [comment]
@leecalcote Yes this can be considered as an option, @kanishkarj suppose we put the generated client & server stubs in the gitignore, will it affect the SMPS package? I guess it yes.

**Comment by kanishkarj** [comment]
I think it would. Go won't generate code from protobuf while installing the package right?

**Comment by kanishkarj** [comment]
Something that might work would be to have the generated code in a separate repo and that repo will be a git sub module here. So the CI will just generate the go code from proto spec into that repo and commit and push those changes ?

**Comment by kushthedude** [comment]
Or rather have the auto-generated code in a seperate folder `generated-stubs` & refer from it ?

**Comment by leecalcote** [comment]
If we can treat the root cause, that would be even better. Is this a VS code plug-in that’s auto compiling?

**Comment by kushthedude** [comment]
> If we can treat the root cause, that would be even better. Is this a VS code plug-in that’s auto compiling?

Actually there is no root cause, for SMPS go package to work we need generated stubs to be stored.
