### ISSUE TITLE
Update Issue Templates to reflect that of SMPS

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#75]
**Description**
The [issue templates in this repo](https://github.com/layer5io/service-mesh-performance-specification/tree/master/.github/ISSUE_TEMPLATE) refer to Meshery.

**Expected Behavior**
These templates should refer to the contribution process specific to SMPS that @PluckyPrecious did such a great job of creating.

**Comment by PluckyPrecious** [comment]
Hi @leecalcote I'll look into it, thanks.

**Comment by PluckyPrecious** [comment]
Hi @leecalcote @kushthedude @chandrashritii could you please direct me to the SMP documentation site page? I can't find any, if there isn't then the template will be incomplete. Which means an index.html need to be created.

Your thoughts?

**Comment by leecalcote** [comment]
@PluckyPrecious good question. The issue template from the Meshery repo are a great starting point - https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE. Some of these can be directly copied, while one or two make need a slight tweak to be SMP specific.
