### ISSUE TITLE
Change project name from SMPS to SMP

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#80]
**Current State:**
SMP is shorter and gets people less tripped up. It doesn't need "Specification" in the title. Many people will already add the word _specification_ as a descriptor when describing SMPS, so the "S" often becomes redundant.

**Desired State:**
- [ ] Change this repository's name (drop "specification")
- [ ] Remove the "S" in SMPS in the logo.
- [ ] Update elsewhere....?

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by JubayerJoy** [comment]
Hi, I can work on it!
I will update the Repo name and Logo.
Some places I noticed needs to be changed,
 - [Layer5 Program page](https://layer5.io/projects/service-mesh-performance-specification)
 - [Rename release SMPS v0.1.0 to SMP v0.1.0](https://github.com/layer5io/service-mesh-performance-specification/releases/tag/v0.1.0)
 - [SMPS Readme.md](https://github.com/layer5io/service-mesh-performance-specification)
 - [SMPS webiste mentions](https://smp-spec.io/)

Will that cover it?

**Comment by PluckyPrecious** [comment]
> Hi, I can work on it!
> I will update the Repo name and Logo.
> Some places I noticed needs to be changed,
> 
> Layer5 Program page
> Rename release SMPS v0.1.0 to SMP v0.1.0
> SMPS Readme.md
> SMPS webiste mentions
> 
> Will that cover it?

Awesome! Please do go ahead. 👍🏽

**Comment by leecalcote** [comment]
Oh, no. I just completed this and didn't realize that @JubayerJoy had signed up to work on this. Oops. I'm including SMP in a book that I'm finalizing draft on today (and so it is top of mind). I took a break to make this update.  After which, I find the issue is already assigned. 

There is plenty more where this comes from, though @JubayerJoy. Would you like to review the PR for this issue?

**Comment by JubayerJoy** [comment]
Hi, @leecalcote, I was working on this issue parallel to you, and just noticed the update while sending in the PR. 😥 

I think you should [Rename release SMPS v0.1.0 to SMP v0.1.0](https://github.com/layer5io/service-mesh-performance-specification/releases/tag/v0.1.0) and also should change [Layer5 page](https://layer5.io/projects/service-mesh-performance-specification) if you haven't already.

best wishes for your book! 🎈

**Comment by JubayerJoy** [comment]
I have reviewed the PR, Looks solid ✊
You can use the edited logos from my PR, I'm including [Google drive link](https://drive.google.com/drive/folders/1eZNyrGCvJKCDELWbcBmACosvcOdyo6xT?usp=sharing) so you can download and add them easily to this Repo!
Cheers! 👍

**Comment by PluckyPrecious** [comment]
Weldone @JubayerJoy you rock! 🥳
