### ISSUE TITLE
Two copies of the "Analyzing with SMP" blog

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-performance#88]
**Description**
After the merge of the change from smps to smp, there is an extra copy (a residual copy of this post)

**Expected Behavior**
Only the "SMP" post should remain. 

**Screenshot**
![5C35A1DF-9EF5-4872-920A-EDD9048EF9AA](https://user-images.githubusercontent.com/7570704/89853704-ab40a680-db57-11ea-8d2e-d3c321b3a128.png)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

**Comment by JubayerJoy** [comment]
Hi @leecalcote, I noticed the bug and filed an issue #87.
I have made PR #89 to solve this 👍

**Comment by JubayerJoy** [comment]
@leecalcote, the release tag name is `SMPS v0.1.0`. What is your thought on changing it to `SMP v0.1.0`?
'<img src ="https://i.imgur.com/r1UXqa7.png">

**Comment by leecalcote** [comment]
@JubayerJoy great suggestion. Wow, what an eye for detail. 😄

**Comment by Nikhil-Ladha** [comment]
Closed by #89
