### ISSUE TITLE
[Site] Fix blog layout

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#92]
**Description**

The blog posts on the [smp-spec.io](https://smp-spec.io/) site open in a pop-up box in the same tab.

**Expected Behavior**

The posts should have a post layout (can be copied from the Layer5 blog) and should be set to open in a new tab.

**To Reproduce**
1. Go to 'https://smp-spec.io/'
2. Scroll down to the 'Blog' section.
3. Click on any of the posts.

**Comment by chandrashritii** [comment]
@Neilblaze Do you want to take this up?

**Comment by Neilblaze** [comment]
> @Neilblaze Do you want to take this up?

Yes I can, but atm my exams are going on :sweat_smile:
So, it will be better if it's kept open for some days, if someone takes it up, well and good! :smile: & if don't then rest be assured I'll definitely take this up :laughing:

**Comment by PluckyPrecious** [comment]
Knock knock @manishdangi98 what's the situation report? 😃

**Comment by JubayerJoy** [comment]
Hi @manishdangi98, if you are not working on it, I would love to squash this bug!

**Comment by manishdangi98** [comment]
Sure @JubayerJoy  you can take this

**Comment by Nikhil-Ladha** [comment]
Why was it closed, it has not been solved yet?

**Comment by leecalcote** [comment]
@Nikhil-Ladha, we're going to be showing this site around fairly broadly and so I pushed some changes up after our Websites call on Monday. https://smp-spec.io/blog.

The "page" layout needs improvement, but this converts the site from modal to individual page. @Neilblaze and @JubayerJoy are tracking some excellent suggestions on improvements here - https://docs.google.com/document/d/1EnFMGyPbsQ3h-YuYE0Jutew79NrPzPNTVxLu8rvqRzE/edit

**Comment by Neilblaze** [comment]
Closed via commit [ef5882d71dd6f661f4dca06d639390592c0475fe](https://github.com/layer5io/service-mesh-performance/commit/ef5882d71dd6f661f4dca06d639390592c0475fe)
