### ISSUE TITLE
create netlify build

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/service-mesh-performance#96]
**Description**

Create a netlify build for the [smp-spec.io](https://smp-spec.io/) site, similar to the one present for the layer5.io site on the layer5 repository.

**Comment by chandrashritii** [comment]
@Tanuj22 Would you like to take this one up?

**Comment by Tanuj22** [comment]
@chandrashritii Sure

**Comment by PluckyPrecious** [comment]
@Tanuj22 situation report please. 😃

**Comment by Tanuj22** [comment]
@leecalcote Netlify needs access to the repo. I have requested access from netlify could you check?

**Comment by Nikhil-Ladha** [comment]
Done!
